# Generated by Django 3.2.6 on 2022-09-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='recipient_country',
            field=models.CharField(default=None, max_length=222),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='sender_county',
            field=models.CharField(default=None, max_length=222),
            preserve_default=False,
        ),
    ]
