# Generated by Django 3.1.12 on 2022-04-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_marker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marker',
        ),
    ]
