# Generated by Django 3.1.12 on 2022-05-11 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220511_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='postal_code',
            new_name='apartment_suit',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='provence',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='vat_number',
            new_name='country',
        ),
        migrations.AddField(
            model_name='contact',
            name='postal',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='province',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
