# Generated by Django 3.1.12 on 2022-05-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220511_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='postal',
            field=models.IntegerField(max_length=100),
        ),
    ]
