# Generated by Django 3.1.12 on 2022-05-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
