# Generated by Django 3.1.12 on 2022-05-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
    ]
