# Generated by Django 3.2.6 on 2022-08-08 11:56

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcels', '__first__'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='selected_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=200)),
                ('carrier_name', models.CharField(max_length=200)),
                ('carrier_id', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=200)),
                ('total_charge', models.CharField(max_length=20)),
                ('transit_days', models.CharField(max_length=20)),
                ('extra_charges', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=100, unique=True)),
                ('shpment_reference', models.CharField(max_length=100, unique=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('label_type', models.CharField(default='PDF', max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('services', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=None)),
                ('carrier_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=None)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.items')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.parcel')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='address.address')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipper', to='address.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
