# Generated by Django 3.2.6 on 2022-09-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='selected_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=200)),
                ('carrier_name', models.CharField(max_length=200)),
                ('carrier_id', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=200)),
                ('total_charge', models.CharField(max_length=20)),
                ('transit_days', models.CharField(max_length=20)),
                ('extra_charges', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('shipper_id', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_id', models.CharField(blank=True, max_length=255, null=True)),
                ('parcel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('items_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customs_id', models.CharField(blank=True, max_length=255, null=True)),
                ('commodities_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
