# Generated by Django 3.2.6 on 2022-08-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipments',
            name='carrier_ids',
        ),
        migrations.RemoveField(
            model_name='shipments',
            name='shipment_id',
        ),
        migrations.RemoveField(
            model_name='shipments',
            name='shipper',
        ),
    ]
