# Generated by Django 3.2.6 on 2022-08-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='items_id',
            new_name='parcel_items_id',
        ),
    ]
