# Generated by Django 3.2.6 on 2022-08-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='items',
        ),
    ]
