# Generated by Django 3.2.6 on 2022-08-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_parcel_parcel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='items_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
