# Generated by Django 3.2.6 on 2022-08-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_remove_parcel_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='metadata',
        ),
    ]
