# Generated by Django 3.2.6 on 2022-08-09 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_alter_items_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='metadata',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parcels.items_metadata'),
            preserve_default=False,
        ),
    ]
