# Generated by Django 3.2.6 on 2022-08-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom',
            name='Custom_id',
        ),
        migrations.RemoveField(
            model_name='custom',
            name='certify',
        ),
        migrations.RemoveField(
            model_name='custom',
            name='commercial_invoice',
        ),
        migrations.RemoveField(
            model_name='custom',
            name='commodities',
        ),
        migrations.RemoveField(
            model_name='custom',
            name='content_description',
        ),
        migrations.RemoveField(
            model_name='custom',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='custom',
            name='duty',
        ),
        migrations.RemoveField(
            model_name='custom',
            name='incoterm',
        ),
        migrations.RemoveField(
            model_name='custom',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='custom',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='custom',
            name='options',
        ),
        migrations.RemoveField(
            model_name='custom',
            name='signer',
        ),
    ]
