# Generated by Django 3.2.6 on 2022-08-17 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0002_auto_20220817_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='Custom_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='certify',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='commercial_invoice',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='commodities',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customs.commodities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custom',
            name='content_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='content_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='duty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customs.duty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custom',
            name='incoterm',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='invoice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='invoice_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='options',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customs.custom_options'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custom',
            name='signer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
